// <auto-generated />
using DevDojo.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevDojo.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220201110111_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevDojo.Shared.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Walk dog",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gym",
                            Status = "Todo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Paint",
                            Status = "Doing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Run Marathon",
                            Status = "Done"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Walk cat",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Code",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Send grandma email",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Make Tea",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 9,
                            Name = "fix plug",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Buy gift",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Iron Clothes",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Get groceries",
                            Status = "Backlog"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Get ready for party",
                            Status = "Backlog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
